name: test

on:
  push:
    branches:
      - main
      - "test-me-*"

  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Check Package
        uses: hynek/build-and-inspect-python-package@v1.5

  test:

    needs: [package]

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Download Package
      uses: actions/download-artifact@v3
      with:
        name: Packages
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install pkgs
      run: |
        python -m pip install --upgrade pip
        python -m pip install dist/.[testing]

    - name: Test
      shell: bash
      run: |
        tox run -e py
